USE wtw;

-- Структура таблицы users в laravel:

-- CREATE TABLE users (
--  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
--  name VARCHAR(255) NOT NULL,
--  email VARCHAR(255) NOT NULL UNIQUE,
--  email_verified_at TIMESTAMP NULL,
--  password VARCHAR(255) NOT NULL,
--  remember_token VARCHAR(100) NULL,
--  created_at TIMESTAMP NULL,
--  updated_at TIMESTAMP NULL
--);

ALTER TABLE users
ADD COLUMN avatar VARCHAR(256);

CREATE TABLE serials (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  imdb_id VARCHAR(256) NOT NULL,
  title VARCHAR(256) NOT NULL,
  title_original VARCHAR(256) NOT NULL,
  year TIMESTAMP NOT NULL,
);

CREATE TABLE serials_votes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  serial_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  vote INT NOT NULL
);

CREATE TABLE genres (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  imdb_id VARCHAR(256) NOT NULL,
  title VARCHAR(256) NOT NULL
);

CREATE TABLE genre_serial (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  serial_id BIGINT UNSIGNED NOT NULL,
  genre_id BIGINT UNSIGNED NOT NULL
);

CREATE TABLE seasons (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  serial_id BIGINT UNSIGNED NOT NULL,
  number INT NOT NULL
);

CREATE TABLE episodes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  serial_id BIGINT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  number INT NOT NULL,
  air_date TIMESTAMP NOT NULL
);

CREATE TABLE comments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  episode_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  description TEXT NOT NULL,
  parent_id BIGINT UNSIGNED,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE serials_watched (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  serial_id BIGINT UNSIGNED NOT NULL
);

CREATE TABLE episodes_watched (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  serial_id BIGINT UNSIGNED NOT NULL,
  episode_id BIGINT UNSIGNED NOT NULL
);
